project:
  type: website

website:
  description: "A blog built with Quarto"

  title: "Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: bluesky
        href: https://bsky.app/
format:
  html:
    theme:
      - minty
      - brand
    css: styles.css

execute: 
  freeze: auto



