project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://zanabrilej22.github.io/Reproducible_research_course/

  title: "Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/zanabrilej22
      - icon: linkedin
        href: https://www.linkedin.com/in/žana-brilej-643402201
format:
  html:
    theme:
      - minty
    css: styles.css


sidebar:
  depth: 2
  


execute:
  freeze: auto
