project:
  type: website

website:
  title: "Zana's Blog"
  description: "A week of notes, code, and things I learned."
  site-url: https://zanabrilej22.github.io/Reproducible_research_course/
  navbar:
    right:
      - href: about.qmd
        text: About
      - icon: github
        href: https://github.com/zanabrilej22
      - icon: bluesky
        href: https://bsky.app/
format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
